name: sportpedia_mobile
description: "SportPedia - Gerbang Olahragamu. Langkah Pertama Menuju Arena."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # HTTP requests untuk pemanggilan async ke web service
  http: ^1.2.2

  # State management
  provider: ^6.1.5+1

  # Django auth integration (session management)
  pbp_django_auth: ^0.4.0

  # Fonts
  google_fonts: ^6.1.0

  # Buka URL (misal ke web, wa, dll)
  url_launcher: ^6.3.2

  # Intl untuk formatting tanggal/angka, dll
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
